// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsmessage(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashmessage(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsmessage(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsmessage(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsmessage(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsmessage(lhsKey, rhsKey) {
          if deepEqualsmessage(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsmessage(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashmessage(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashmessage(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashmessage(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashmessage(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashmessage(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashmessage(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Generated class from Pigeon that represents data sent in messages.
struct Book: Hashable {
  var title: String? = nil
  var author: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Book? {
    let title: String? = nilOrValue(pigeonVar_list[0])
    let author: String? = nilOrValue(pigeonVar_list[1])

    return Book(
      title: title,
      author: author
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      author,
    ]
  }
  static func == (lhs: Book, rhs: Book) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsmessage(lhs.title, rhs.title) && deepEqualsmessage(lhs.author, rhs.author)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Book")
    deepHashmessage(value: title, hasher: &hasher)
    deepHashmessage(value: author, hasher: &hasher)
  }
}

private class MessagePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return Book.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Book {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagePigeonCodecWriter(data: data)
  }
}

class MessagePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagePigeonCodec(readerWriter: MessagePigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BookApi {
  func getBookDetails(isbn: String) throws -> Book
  func downlodBook(isbn: String, completion: @escaping (Result<Void, Error>) -> Void)
  func sum(a: Double, b: Double) throws -> Double
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BookApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagePigeonCodec.shared }
  /// Sets up an instance of `BookApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BookApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getBookDetailsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.example.common_plugin_set.BookApi.getBookDetails\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBookDetailsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isbnArg = args[0] as! String
        do {
          let result = try api.getBookDetails(isbn: isbnArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBookDetailsChannel.setMessageHandler(nil)
    }
    let downlodBookChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.example.common_plugin_set.BookApi.downlodBook\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      downlodBookChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isbnArg = args[0] as! String
        api.downlodBook(isbn: isbnArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      downlodBookChannel.setMessageHandler(nil)
    }
    let sumChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.example.common_plugin_set.BookApi.sum\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sumChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let aArg = args[0] as! Double
        let bArg = args[1] as! Double
        do {
          let result = try api.sum(a: aArg, b: bArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sumChannel.setMessageHandler(nil)
    }
  }
}
