// Autogenerated from Pigeon (v27.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum PaymentApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum Environment: Int {
  case sandbox = 0
  case production = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct PaymentConfig: Hashable, CustomStringConvertible {
  var environment: Environment
  var merchantId: String
  var publicKey: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PaymentConfig? {
    let environment = pigeonVar_list[0] as! Environment
    let merchantId = pigeonVar_list[1] as! String
    let publicKey = pigeonVar_list[2] as! String

    return PaymentConfig(
      environment: environment,
      merchantId: merchantId,
      publicKey: publicKey
    )
  }
  func toList() -> [Any?] {
    return [
      environment,
      merchantId,
      publicKey,
    ]
  }
  static func == (lhs: PaymentConfig, rhs: PaymentConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PaymentApiPigeonInternal.deepEquals(lhs.environment, rhs.environment) && PaymentApiPigeonInternal.deepEquals(lhs.merchantId, rhs.merchantId) && PaymentApiPigeonInternal.deepEquals(lhs.publicKey, rhs.publicKey)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PaymentConfig")
    PaymentApiPigeonInternal.deepHash(value: environment, hasher: &hasher)
    PaymentApiPigeonInternal.deepHash(value: merchantId, hasher: &hasher)
    PaymentApiPigeonInternal.deepHash(value: publicKey, hasher: &hasher)
  }

  public var description: String {
    return "PaymentConfig(environment: \(String(describing: environment)), merchantId: \(String(describing: merchantId)), publicKey: \(String(describing: publicKey)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PaymentRequest: Hashable, CustomStringConvertible {
  var amount: Double
  var currency: String
  var transactionId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PaymentRequest? {
    let amount = pigeonVar_list[0] as! Double
    let currency = pigeonVar_list[1] as! String
    let transactionId = pigeonVar_list[2] as! String

    return PaymentRequest(
      amount: amount,
      currency: currency,
      transactionId: transactionId
    )
  }
  func toList() -> [Any?] {
    return [
      amount,
      currency,
      transactionId,
    ]
  }
  static func == (lhs: PaymentRequest, rhs: PaymentRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PaymentApiPigeonInternal.deepEquals(lhs.amount, rhs.amount) && PaymentApiPigeonInternal.deepEquals(lhs.currency, rhs.currency) && PaymentApiPigeonInternal.deepEquals(lhs.transactionId, rhs.transactionId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PaymentRequest")
    PaymentApiPigeonInternal.deepHash(value: amount, hasher: &hasher)
    PaymentApiPigeonInternal.deepHash(value: currency, hasher: &hasher)
    PaymentApiPigeonInternal.deepHash(value: transactionId, hasher: &hasher)
  }

  public var description: String {
    return "PaymentRequest(amount: \(String(describing: amount)), currency: \(String(describing: currency)), transactionId: \(String(describing: transactionId)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PaymentResult: Hashable, CustomStringConvertible {
  var title: String
  var result: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PaymentResult? {
    let title = pigeonVar_list[0] as! String
    let result = pigeonVar_list[1] as! String

    return PaymentResult(
      title: title,
      result: result
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      result,
    ]
  }
  static func == (lhs: PaymentResult, rhs: PaymentResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PaymentApiPigeonInternal.deepEquals(lhs.title, rhs.title) && PaymentApiPigeonInternal.deepEquals(lhs.result, rhs.result)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PaymentResult")
    PaymentApiPigeonInternal.deepHash(value: title, hasher: &hasher)
    PaymentApiPigeonInternal.deepHash(value: result, hasher: &hasher)
  }

  public var description: String {
    return "PaymentResult(title: \(String(describing: title)), result: \(String(describing: result)))"
  }
}

private class PaymentApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return Environment(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return PaymentConfig.fromList(self.readValue() as! [Any?])
    case 131:
      return PaymentRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return PaymentResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PaymentApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Environment {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PaymentConfig {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PaymentRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PaymentResult {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PaymentApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PaymentApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PaymentApiPigeonCodecWriter(data: data)
  }
}

class PaymentApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PaymentApiPigeonCodec(readerWriter: PaymentApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PaymentGateway {
  func initialize(config: PaymentConfig, completion: @escaping (Result<Void, Error>) -> Void)
  func makePayment(request: PaymentRequest, completion: @escaping (Result<PaymentResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PaymentGatewaySetup {
  static var codec: FlutterStandardMessageCodec { PaymentApiPigeonCodec.shared }
  /// Sets up an instance of `PaymentGateway` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PaymentGateway?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.example.common_plugin_set.PaymentGateway.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! PaymentConfig
        api.initialize(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let makePaymentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.example.common_plugin_set.PaymentGateway.makePayment\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      makePaymentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PaymentRequest
        api.makePayment(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      makePaymentChannel.setMessageHandler(nil)
    }
  }
}
